dependencies:
- name: eas-candidate-attendance-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.124
- name: eas-exodus-admin
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.105
- name: eas-exodus-ws
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.293
- name: eas-healthchecks
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.344
- name: eas-mailhog
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.43
- name: eas-payeezy-stub
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.35
- name: eas-payeezy-ws
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.115
- name: eas-selt-financial-document
  repository: http://jenkins-x-chartmuseum:8080
  version: 6.0.29
- name: eas-selt-ovp-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.1.34
- name: eas-selt-results-service
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.76
- name: eas-selt-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.310
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: expose
- name: exposecontroller
  version: 2.3.118
  repository: http://chartmuseum.jenkins-x.io
  alias: cleanup
