dependencies:
- name: eas-selt-results-service
  repository: https://chartmuseum-jx.psiac.net
  version: 1.0.76
- name: eas-selt-web
  repository: https://chartmuseum-jx.psiac.net
  version: 1.0.310
#- name: exposecontroller
#  version: 2.3.118
#  repository: http://chartmuseum.jenkins-x.io
#  alias: expose
#- name: exposecontroller
#  version: 2.3.118
#  repository: http://chartmuseum.jenkins-x.io
#  alias: cleanup
